name: LarcRobot
max_hsv_blue:
  - 100
  - 40
  - 50
min_hsv_blue:
  - 150
  - 60
  - 70
max_hsv_green:
  - 200
  - 80
  - 90
min_hsv_green:
  - 250
  - 10
  - 20
max_hsv_red:
  - 50
  - 30
  - 40
min_hsv_red:
  - 112
  - 50
  - 60
max_hsv_black:
  - 114
  - 70
  - 80
min_hsv_black:
  - 116
  - 90
  - 10