max_hsv_black: [360, 66, 35]
max_hsv_blue: [270, 100, 100]
max_hsv_green: [180, 100, 100]
max_hsv_red: [340, 100, 100]
min_hsv_black: [0, 0, 0]
min_hsv_blue: [185, 45, 20]
min_hsv_green: [60, 25, 22]
min_hsv_red: [20, 23, 26]
name: LarcRobot
ref_s: 0.25
ref_x: 155
ref_y: 346
